development:
  adapter: postgresql
  encoding: unicode
  database: blogaday_dev
  pool: 5
  username: blogaday
  password: blogaday

test:
  adapter: postgresql
  encoding: unicode
  database: blogaday_test
  pool: 5
  username: blogaday
  password: blogaday
